CREATE DATABASE userdb;

USE userdb;

CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('ACCOUNT_MANAGER', 'ADMIN', 'EMPLOYEE') NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);
